### ISSUE TITLE
Hcc Cor, DNN9.1.1 and AppendHeader

### ISSUE THREAD

**Issue by kurtwilbies** [HotcakesCommerce/core#32]
I'am testing HCC in DNN9.1.1 and constantly getting the following error:

	-	Server cannot append header after HTTP headers have been sent.
	-	at System.Web.HttpResponse.AppendHeader(String name, String value)
		at System.Web.HttpResponseWrapper.AddHeader(String name, String value)
		at System.Web.Helpers.AntiXsrf.AntiForgeryWorker.GetFormInputElement(HttpContextBase httpContext)
		at System.Web.Helpers.AntiForgery.GetHtml()
		at DotNetNuke.Framework.ServicesFrameworkImpl.RegisterAjaxAntiForgery(Page page)
		at DotNetNuke.Framework.PageBase.OnPreRender(EventArgs e)
		at DotNetNuke.Framework.DefaultPage.OnPreRender(EventArgs evt)
		at System.Web.UI.Control.PreRenderRecursiveInternal()
		at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by hismightiness** [comment]
Another issue and pull request has resolved this error, but there may be multiple scenarios where this error exists.  Please include specific steps to reproduce this error so someone can troubleshoot it.

**Comment by hismightiness** [comment]
Hello @kurtwilbies ...  Can you please provide the specific steps you took to produce and reproduce the exception you reported so we can triage this issue and verify if it's completely resolved?
