### ISSUE TITLE
HCC core, DNN9.1.1 and MVC

### ISSUE THREAD

**Issue by kurtwilbies** [HotcakesCommerce/core#34]
I'am testing HCC in DNN9.1.1 and constantly getting the following error (using both the current DNN9.1.1 MVC assembly AND HCC, slightly older, MVC assembly (version)):

	-	Error executing child request for handler 'System.Web.Mvc.HttpHandlerUtil+ServerExecuteHttpHandlerAsyncWrapper'.	
	-	at System.Web.HttpServerUtility.ExecuteInternal(IHttpHandler handler, TextWriter writer, Boolean preserveForm, Boolean setPreviousPage, VirtualPath path, VirtualPath filePath, String physPath, Exception error, String queryStringOverride)
	    at System.Web.HttpServerUtility.Execute(IHttpHandler handler, TextWriter writer, Boolean preserveForm, Boolean setPreviousPage)
	    at System.Web.HttpServerUtility.Execute(IHttpHandler handler, TextWriter writer, Boolean preserveForm)
	    at System.Web.Mvc.Html.ChildActionExtensions.ActionHelper(HtmlHelper htmlHelper, String actionName, String controllerName, RouteValueDictionary routeValues, TextWriter textWriter)
	    at System.Web.Mvc.Html.ChildActionExtensions.Action(HtmlHelper htmlHelper, String actionName, String controllerName, RouteValueDictionary routeValues)
	    at Hotcakes.Commerce.Dnn.Mvc.MvcRenderingEngine.Render(String controllerName, String actionName, String viewName, Object routeValues)
	    at Hotcakes.Modules.Checkout.CheckoutView.RenderView()
	    at Hotcakes.Commerce.Dnn.Web.HotcakesModuleBase.OnLoad(EventArgs e)

**Comment by hismightiness** [comment]
Please add more details on how to duplicate the error.  I've been testing in 9.1.1 through 9.6.0 and can't duplicate the error.  Same with the issue I just removed from this milestone.  Sorry.  :(

**Comment by moorecreative** [comment]
@kurtwilbies this is an older ticket, but if anyone else stops here on the search for an issue with regards to Hotcakes version 3.5 upgrade, then look to this location for information
https://hotcakes.org/Forums/g/Posts/t/401/Exception-upgrading-to-HCC-3-5-0
