### ISSUE TITLE
HCC core, DNN9.1.1 and Cookies 

### ISSUE THREAD

**Issue by kurtwilbies** [HotcakesCommerce/core#35]
I'am testing HCC in DNN9.1.1 and constantly getting the following error:

	-	Server cannot modify cookies after HTTP headers have been sent.
	-	at System.Web.HttpResponse.BeforeCookieCollectionChange()
	    at System.Web.HttpCookieCollection.Set(HttpCookie cookie)
	    at System.Web.Helpers.AntiXsrf.AntiForgeryWorker.GetFormInputElement(HttpContextBase httpContext)
	    at System.Web.Helpers.AntiForgery.GetHtml()
	    at DotNetNuke.Framework.ServicesFrameworkImpl.RegisterAjaxAntiForgery(Page page)
	    at DotNetNuke.Framework.PageBase.OnPreRender(EventArgs e)
	    at DotNetNuke.Framework.DefaultPage.OnPreRender(EventArgs evt)
	    at System.Web.UI.Control.PreRenderRecursiveInternal()
	    at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by hismightiness** [comment]
Removed from the milestone. We need more information to duplicate the error.

**Comment by hismightiness** [comment]
Hello @kurtwilbies ...  Can you please provide the specific steps you took to produce and reproduce the exception you reported so we can triage this issue?
