### ISSUE TITLE
Source array was not long enough. Check srcIndex and length, and the array's lower bounds.

### ISSUE THREAD

**Issue by sbwalker** [HotcakesCommerce/core#7]
The application will sometimes throw an error "Source array was not long enough. Check srcIndex and length, and the array's lower bounds." which will leave it in an unrecoverable error state. The only resolution is to restart the application which will immediately resolve the issue. The rest of the error details are included below:

   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Collections.Generic.List`1.Insert(Int32 index, T item)
   at System.Web.Mvc.ViewEngineCollection.InsertItem(Int32 index, IViewEngine item)
   at Hotcakes.Commerce.Dnn.Providers.HccUrlRoutingModule.RegisterViewEngines(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by hismightiness** [comment]
For anyone experiencing this issue today, a temporary workaround you can employ right now is to increase the frequency at which your application pool recycles itself.
